### ISSUE TITLE
Hinzufügen neuer Symbole

### ISSUE THREAD

**Issue by DerMusicus** [Fuehrungsharke/Fuehrungsharke.github.io#16]
Ich habe versucht das Symbol für Boote einzufügen, bekomme aber eine Exception im Browser, wenn ich versuche ein Boot in den Graphen einzufügen:
`Uncaught TypeError: signSvg.childNodes[0].setAttribute is not a function
    at getSignSvg (canvas.js:42:27)
    at drawSign (canvas.js:74:23)
    at canvas.js:114:13
    at Array.forEach (<anonymous>)
    at drawItem (canvas.js:113:20)
    at drawRecursive (canvas.js:194:16)
    at drawItem (canvas.js:163:35)
    at drawRecursive (canvas.js:194:16)
    at drawItem (canvas.js:163:35)
    at drawRecursive (canvas.js:187:28)`

[feature/include_water_vehicle](https://github.com/Fuehrungsharke/Fuehrungsharke.github.io/tree/feature/include_water_vehicle)

**Comment by DerMusicus** [comment]
Nach dem der Header aus dem neuen SVG entfernt wurde, geht es. Hier sollten wir gucken, warum der Header die Function auf die Bretter schickt
